# 元组

## 基本操作

与列表类似，元组是一个有序序列，但是不可变。

元组用小括号`()`生成：

In [2]:
t = (10, 11, 12, 13, 14)

In [3]:
t

(10, 11, 12, 13, 14)

可以索引，切片：

In [4]:
t[0]

10

In [5]:
t[1:3]

(11, 12)

元组是不可变的，不能通过赋值改变：

In [6]:
t[0] = 1

TypeError: 'tuple' object does not support item assignment

## 单元素的元组生成

由于()在表达式中被应用，只含有单个元素的元组容易和表达式混淆，所以采用下列方式定义只有一个元素的元组：

In [15]:
a = (10)  # 定义只有一个元素的元组需要在后面加上逗号，此处定义的a为int类型

In [16]:
a

10

In [17]:
type(a)

int

In [19]:
a = (10,)  # 定义只有一个元素的元组需要在后面加上逗号，此处定义的a为tuple类型

In [20]:
a

(10,)

In [21]:
type(a)

tuple

## 列表与元组的转换

用构造方法`list`和`tuple`可以相互转换：

In [22]:
a = [10, 11, 12, 13, 14]

In [23]:
tuple(a)

(10, 11, 12, 13, 14)

In [24]:
a = (10, 11, 12, 13, 14)

In [25]:
list(a)

[10, 11, 12, 13, 14]

## 元组方法

由于元组是不可变的，所以只能有一些不可变自身的方法，例如计算元素个数`.count()`方法和元素位置`.index()`方法，用法与列表一样：

In [26]:
a = (10, 11, 12, 13, 14)

In [27]:
a.count(10)

1

In [28]:
a.index(12)

2

## 列表与元组的速度比较

IPython 中用 `magic` 命令 `%timeit` 来计时。

比较列表与元组的生成速度：

In [29]:
%timeit -n 100000 [1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25]  # 列表

47.4 ns ± 2.76 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [30]:
%timeit -n 100000 (1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25)  # 元组

6.63 ns ± 0.155 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


在遍历上，元组和列表的速度表现差不多。

产生内容相同的随机列表和元组：

In [33]:
from numpy.random import rand

values = rand(10000,4)
print(values)
lst = [list(row) for row in values]
tup = tuple(tuple(row) for row in values)

[[0.04869201 0.94178438 0.6936699  0.11721114]
 [0.82117116 0.17020705 0.62800795 0.73986837]
 [0.37421787 0.61745412 0.48753364 0.45466889]
 ...
 [0.31808467 0.4529173  0.96591877 0.6818706 ]
 [0.06614661 0.50771565 0.54067106 0.56037663]
 [0.32563961 0.08801482 0.93365377 0.24069276]]


In [35]:
%timeit -n 100 for row in lst: tuple(row)

243 µs ± 6.41 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [36]:
%timeit -n 100 for row in tup: tuple(row)

160 µs ± 6.15 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


比较遍历和索引速度：

In [38]:
%timeit -n 100 for row in lst: a = row[0] + 1

605 µs ± 52.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [39]:
%timeit for row in tup: a = row[0] + 1

591 µs ± 21.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


总结：元组的生成速度会比列表快很多，迭代速度快一点，索引速度差不多。

## 元组与多变量赋值

Python支持多变量赋值的模式：

In [40]:
a, b = 1, 2

In [41]:
a

1

In [42]:
b

2

Python中的多变量赋值，本质是两个元组中的元素进行一一对应，此时，等号两边的元素数目必须相等。例如，将包含两个元素的元组t的值分别赋给a和b：

In [43]:
t = (1, 2)

In [44]:
a, b = t

In [46]:
a, b

(1, 2)

利用多变量赋值，变量的交换可以用一行代码实现：

In [47]:
a, b = b, a

In [49]:
a, b

(2, 1)

多变量赋值支持超过两个值的操作，只要等号两边的元素数相同：

In [50]:
a, b, c = 1, 2, 3

嵌套：

In [51]:
a, (b, c) = 1, (2, 3)

带星号的赋值，将后面的值都变成一个列表给某个变量赋值：

In [52]:
a, *b = 1, 2, 3

In [54]:
a, b

(1, [2, 3])