## 数组操作

### 数值相关的操作

可以使用`.sum()`方法进行求和：

In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])

In [7]:
print(a)

[[1 2 3]
 [4 5 6]]


In [8]:
a.sum()

21

默认对所有元素求和，可以通过`axis`参数指定求和维度：

In [9]:
print(a.sum(axis=0))

[5 7 9]


In [12]:
a.sum(axis=1)

array([ 6, 15])

In [20]:
arr = np.array([1, 2])
arrT = arr.T
print(arr, arrT)
arr == arrT, arr is arrT, arr.shape, arrT.shape  # arrT是arr的转置

[1 2] [1 2]


(array([ True,  True]), False, (2,), (2,))

指定维度时，相当于沿着指定的维度进行求和，因此，对于形状为(2,3)的数组，指定第0维会将第0维消去，得到形状为(3,)的数组，指定第1维会将第1维消去，得到形状为(2,)的数组。

与之对应还有个`np.sum()`函数，得到相同的操作结果：

In [21]:
np.sum(a)

21

该函数可以作用在与数组类似的对象上：

In [22]:
np.sum([[1, 2, 3], [4, 5, 6]])

21

`.prod()`方法和`np.prod()`函数可以实现求积操作，与`.sum()`方法类似：

In [23]:
a.prod()

720

In [24]:
a, np.prod(a, axis=1)

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([  6, 120]))

`.max()`和`.min()`函数可以实现求最值的操作，也支持指定维度：

In [25]:
a.max()

6

In [26]:
a.min()

1

In [27]:
a.max(axis=-1)

array([3, 6])

In [28]:
a.min(axis=0)

array([1, 2, 3])

对应的函数形式分别为`np.max()`和`np.min()`。

`.argmax()`和`.argmin()`函数可以分别返回最大值和最小值的位置：

In [29]:
a.argmax()

5

a是一个(2,3)的数组，索引5是不存在的，`.argmax()`方法返回的是将a看成一维数组时最大值的位置。

指定维度时，它返回的是对应维度中最值的位置：

In [30]:
a.argmin(axis=0)

array([0, 0, 0], dtype=int64)

对应的函数形式分别为`np.argmax()`和`np.argmin()`。

均值`.mean()`方法和`np.mean()`函数：

In [31]:
a.mean()

3.5

In [32]:
a.mean(axis=1)

array([2., 5.])

标准差`.std()`方法和`np.std()`函数，方差`.var()`方法和`np.var()`函数：

In [33]:
a.std()

1.707825127659933

In [34]:
a.std(axis=1)

array([0.81649658, 0.81649658])

In [35]:
a.var()

2.9166666666666665

`.round()`方法会将数组近似到整数：

In [38]:
a = np.array([1.35, 2.56, 1.5, 3.1])

In [39]:
a.round()

array([1., 3., 2., 3.])

### 形状相关的操作

使用`.shape`属性可以直接修改数组的形状：

In [40]:
a = np.array([8, 6, 5, 7, 1, 4, 2, 3])

In [41]:
a.shape

(8,)

In [42]:
a

array([8, 6, 5, 7, 1, 4, 2, 3])

In [43]:
a.shape = 2, 4

In [44]:
a

array([[8, 6, 5, 7],
       [1, 4, 2, 3]])

可以使用`.reshape()`方法得到一个新数组，但是不改变原来的数组：

In [45]:
a.reshape(4, 2)

array([[8, 6],
       [5, 7],
       [1, 4],
       [2, 3]])

In [46]:
a

array([[8, 6, 5, 7],
       [1, 4, 2, 3]])

形状可以增加一个`-1`参数，当某个维度为`-1`时，`NumPy`会自动根据其他维度计算：

In [47]:
a.reshape(-1, 2)

array([[8, 6],
       [5, 7],
       [1, 4],
       [2, 3]])

可以调用`.resize()`方法改变原来数组的形状：

In [48]:
a.resize(8)

In [49]:
a

array([8, 6, 5, 7, 1, 4, 2, 3])

`.resize()`方法不支持`-1`参数，但是支持形状不对应的修改，缺少的部分会补`0`：

In [50]:
b = np.array([1, 2, 3, 4, 5, 6, 7, 8])

In [51]:
b.resize(2, 5)

In [52]:
b

array([[1, 2, 3, 4, 5],
       [6, 7, 8, 0, 0]])

np.newaxis可以扩展数组的维度，通常配合索引使用，增加一个大小为1的新维度：

In [53]:
a = np.arange(3)

In [54]:
a.shape

(3,)

In [55]:
a[np.newaxis, :]

array([[0, 1, 2]])

In [56]:
a.shape

(3,)

In [57]:
a[np.newaxis, :, np.newaxis]

array([[[0],
        [1],
        [2]]])

In [58]:
a.shape

(3,)

`np.newaxis`是`None`的别名，也可以直接使用`None`代替它：

In [59]:
np.newaxis is None

True

`.squeeze()`方法返回一个去掉所有大小为1的维度的新数组，原数组不改变：

In [60]:
a.shape = 1, 3, 1

In [61]:
a

array([[[0],
        [1],
        [2]]])

In [64]:
a.squeeze(), a.squeeze().shape

(array([0, 1, 2]), (3,))

In [63]:
a.shape

(1, 3, 1)

数组的转置：

In [65]:
a = np.arange(30)

In [66]:
a.shape = 5, 6

In [67]:
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [68]:
a.T

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [70]:
a is a.T

False

In [71]:
a.transpose()

array([[ 0,  6, 12, 18, 24],
       [ 1,  7, 13, 19, 25],
       [ 2,  8, 14, 20, 26],
       [ 3,  9, 15, 21, 27],
       [ 4, 10, 16, 22, 28],
       [ 5, 11, 17, 23, 29]])

In [72]:
a.shape = 1, 2, 3, 5

In [73]:
a.T.shape

(5, 3, 2, 1)

### 数组的连接操作

In [74]:
a = np.arange(6)

In [75]:
a.shape = 2, 3

In [76]:
a

array([[0, 1, 2],
       [3, 4, 5]])

In [77]:
b = np.arange(10, 16)

In [78]:
b.shape = 2, 3

In [79]:
b

array([[10, 11, 12],
       [13, 14, 15]])

连接两个数组可以使用`np.concatenate()`函数：

In [80]:
x = np.concatenate((a, b))

In [81]:
x.shape

(4, 3)

In [82]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

默认情况下，`np.concatenate()`函数会沿着第0维开始进行连接。连接的维度可以通过`axis`指定：

In [83]:
x = np.concatenate((a, b), axis=1)

In [85]:
x.shape, x

((2, 6),
 array([[ 0,  1,  2, 10, 11, 12],
        [ 3,  4,  5, 13, 14, 15]]))

理论上说，a和b的形状一样，还可以让他们沿着第2维进行连接，得到一个(2,3,2)的数组。但是`np.concatenate()`函数不支持直接使用这个的操作。为了解决这个问题，可以使用`np.atleast_1d(),np.atleast_2d(),np.atleast_3d()`函数将数组扩展：

In [86]:
x = np.concatenate(np.atleast_3d(a, b), axis=2)

In [88]:
x.shape, x

((2, 3, 2),
 array([[[ 0, 10],
         [ 1, 11],
         [ 2, 12]],
 
        [[ 3, 13],
         [ 4, 14],
         [ 5, 15]]]))

`np.atleast_xd()`函数系列的运作规则如下：

- `np.atleast_xd()`函数系列对于大于等于x维的数组不起作用。
- 对于形状为(N,)的数组，`np.atleast_2d()`函数将其转变为形状为(1,N)的数组。
- 对于形状为(N,)的数组，`np.atleast_3d()`函数将其转变为形状为(1,N,1)的数组。
- 对于形状为(M,N)的数组，`np.atleast_3d()`函数将其转变为形状为(M,N,1)的数组。

对于常用的沿着第0,1,2三维的操作，NumPy提供了以下三个函数`np.vstack(),np.hstack(),np.dstack()`，完成各个方法的连接操作：

In [89]:
a.shape

(2, 3)

In [90]:
b.shape

(2, 3)

In [91]:
np.vstack((a, b))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [10, 11, 12],
       [13, 14, 15]])

In [92]:
np.hstack((a, b))

array([[ 0,  1,  2, 10, 11, 12],
       [ 3,  4,  5, 13, 14, 15]])

In [93]:
np.dstack((a, b))

array([[[ 0, 10],
        [ 1, 11],
        [ 2, 12]],

       [[ 3, 13],
        [ 4, 14],
        [ 5, 15]]])

### 数组的四则运算，点乘和矩阵运算

In [94]:
a = np.array([[1, 2], [3, 4]])

四则运算：

In [95]:
a * a  # 乘法是对应元素相乘

array([[ 1,  4],
       [ 9, 16]])

In [96]:
a + a

array([[2, 4],
       [6, 8]])

In [97]:
a / a

array([[1., 1.],
       [1., 1.]])

In [98]:
a - a

array([[0, 0],
       [0, 0]])

In [99]:
a ** 2

array([[ 1,  4],
       [ 9, 16]])

In [100]:
a + 2

array([[3, 4],
       [5, 6]])

点乘，即矩阵运算：

In [101]:
a.dot(a)

array([[ 7, 10],
       [15, 22]])

In [102]:
np.dot(a, a)

array([[ 7, 10],
       [15, 22]])

Python 3提供了`@`操作符完成点乘操作：

In [103]:
a @ a

array([[ 7, 10],
       [15, 22]])

### 数组的数学操作

In [104]:
np.pi

3.141592653589793

三角函数：

In [105]:
a = np.linspace(0, np.pi, 4)  # 生成一个0到pi的数组，分成4份

In [106]:
a

array([0.        , 1.04719755, 2.0943951 , 3.14159265])

In [107]:
np.cos(a)

array([ 1. ,  0.5, -0.5, -1. ])

In [108]:
np.exp(a)

array([ 1.        ,  2.84965391,  8.1205274 , 23.14069263])

In [109]:
np.sqrt(a)

array([0.        , 1.02332671, 1.44720251, 1.77245385])

### 数组的逻辑与比较操作

In [110]:
a = np.arange(6)

In [111]:
a > 3

array([False, False, False, False,  True,  True])

In [112]:
a[a > 3]

array([4, 5])

In [113]:
a <= a

array([ True,  True,  True,  True,  True,  True])

不能用 `==` 符号判断两个数组是否相等：

In [114]:
a == a

array([ True,  True,  True,  True,  True,  True])

In [116]:
b = a
c = np.arange(6)
a == b, a == c, b == c, a is b, a is c, b is c

(array([ True,  True,  True,  True,  True,  True]),
 array([ True,  True,  True,  True,  True,  True]),
 array([ True,  True,  True,  True,  True,  True]),
 True,
 False,
 False)

判断相等需要用 `np.all()` 方法：

In [117]:
np.all(a == a)

True

不过考虑到浮点数的精度问题，所以一般用 `np.allclose()` 方法：

In [119]:
np.allclose(a, a), np.allclose(a, b), np.allclose(a, c)

(True, True, True)

`np.nan`是一个特殊的值，它做判断的时候当`False`用，且与任何数进行比较都是`False`，包括它自己：

In [120]:
np.nan == np.nan

False

为了判断一个值是否为`np.nan`，需要使用`np.isnan()`函数：

In [121]:
np.isnan(np.nan)

True

In [122]:
b = np.array([np.inf, -np.inf, np.nan])

In [123]:
np.isnan(b)

array([False, False,  True])

In [124]:
np.isinf(b)

array([ True,  True, False])