# 数组广播机制

数组支持广播机制，支持对一些形状不同但满足一定条件的多个数组进行一些二元操作：

In [1]:
import numpy as np

数组形状相同的情况：

In [2]:
a = np.array([1.0, 2.0, 3.0])

In [3]:
b = np.array([2.0, 2.0, 2.0])

In [4]:
a.shape

(3,)

In [5]:
b.shape

(3,)

也有两个不同维度操作的例子，如数组的数乘：

In [6]:
c = 2.0

In [7]:
a * c

array([2., 4., 6.])

In [8]:
np.shape(c)

()

再看一个更复杂的例子：

In [9]:
a = np.array([
    [0, 0, 0],
    [10, 10, 10],
    [20, 20, 20],
    [30, 30, 30],
])

In [10]:
b = np.array([
    [0, 1, 2],
    [0, 1, 2],
    [0, 1, 2],
    [0, 1, 2],
])

In [11]:
a + b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

将`b`的形状改为(3,)的一维数组：

In [12]:
b = np.array([0, 1, 2])

In [14]:
b.shape, b

((3,), array([0, 1, 2]))

In [15]:
a.shape, a

((4, 3),
 array([[ 0,  0,  0],
        [10, 10, 10],
        [20, 20, 20],
        [30, 30, 30]]))

此时，加法仍然成立：

In [16]:
a + b  # b的形状被自动改为(4,3)，广播机制

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22],
       [30, 31, 32]])

再将a的形状修改为一个(4,1)的数组：

In [17]:
a = np.array([0, 10, 20, 30])

In [18]:
a.shape = 4, 1

In [28]:
a, print(a)

[[ 0]
 [10]
 [20]
 [30]]


(array([[ 0],
        [10],
        [20],
        [30]]),
 None)

In [27]:
print(b)

[0 1 2]


In [20]:
b.shape

(3,)

此时，加法依然成立：

In [26]:
print(a, '\n', b, '\n', a + b)  # a的形状被自动改为(4,3)，广播机制

[[ 0]
 [10]
 [20]
 [30]] 
 [0 1 2] 
 [[ 0  1  2]
 [10 11 12]
 [20 21 22]
 [30 31 32]]


在上面的例子中，两个数组的形状虽然不一样，但是加法操作仍然适用。这是由于NumPy数组存在广播机制（Broadcasting）导致的。

在广播机制下，当两个数组进行二元操作时，NumPy会对它们的形状进行检查，如果两个数组形状匹配，NumPy会按照一定的规则将它们变成两个形状相同的数组，再进行相应的二元操作。

在广播机制中，两个数组的匹配规则如下：
- 规则1：两个数组的形状完全一致。
- 规则2：两个数组的维度一样，对应的维度大小相同，或者其中一个大小为1。
- 规则3：两个数组的维度个数不同时，在低维数组前增加大小为1的维度直到与高维数组维度相等，然后应用前两个规则判断。

匹配成功后，结果数组每个维度的大小取两个数组对应维度大小较大的一个。利用广播机制，不难解释上面例子中的运算过程：

形状相同的加法：
```
a：4×3
b：4×3
```
规则1适用。

只改b的加法：
```
a：4×3
b：  3
```
先根据规则3，将b扩展成(1,3)，再根据规则2匹配成功。

再改a的加法：
```
a：4×1
b：  3
```
先根据规则3，将b扩展成(1,3)，再根据规则2匹配成功。

更复杂的例子：
```
a   ：3d array - 256 x 256 x 3	
b   ：1d array -             3
res ：3d array - 256 x 256 x 3
```

```
a   ：4d array - 8 x 1 x 6 x 1
b   ：3d array -     7 x 1 x 5
res ：3d array - 8 x 7 x 6 x 5
```

```
a   ：2d array - 4 x 1	
b   ：1d array -     3
res ：2d array - 4 x 3
```